name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: make install

      - name: Run linting (if configured)
        run: make lint
        continue-on-error: true

      - name: Run tests
        run: make test
        continue-on-error: true

      - name: Build package
        run: make build

      - name: Verify build output
        run: make info

      - name: Test package installation
        run: |
          npm pack
          npm install -g ./vonage-vonage-mcp-server-api-bindings-*.tgz
          echo "Package installed successfully"

  package-validation:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: make install

      - name: Build package
        run: make build

      - name: Validate package.json
        run: make info

      - name: Dry run publish
        run: make validate