name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: make install

      - name: Check code formatting
        run: make format-check

      - name: Run linting
        run: make lint

      - name: Run type checking
        run: make typecheck

      - name: Run tests
        run: make test
        continue-on-error: true

      - name: Build package
        run: make build

      - name: Verify build output
        run: make info

      - name: Test package installation
        run: |
          npm pack
          npm install -g ./vonage-vonage-mcp-server-api-bindings-*.tgz
          echo "Package installed successfully"

  package-validation:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: make install

      - name: Run all quality checks
        run: make check

      - name: Build package
        run: make build

      - name: Validate package.json
        run: make info

      - name: Dry run publish
        run: make validate
